version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitAndTPPProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAGitAndTPPProject
  gitUsername: siqagituser
  gitBranch: main
services:
- serviceName: project.siqagitandtpp.integrations:GitSyncTest
  packages:
  - name: SIQAGitAndTPPProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.890
