version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitAndTPPProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAGitAndTPPProject
  gitUsername: siqagituser
  gitBranch: main
