version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGitAndTPPProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQAGitAndTPPProject
  gitUsername: siqagituser
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
services:
- serviceName: project.siqagitandtpp.integrations:GitSyncTest
  packages:
  - name: SIQAGitAndTPPProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.890
- serviceName: project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:DatabaseNewAccount
  packages:
  - name: SIQAGitAndTPPProject
    version: "1.0"
- serviceName: project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQAGitAndTPPProject
    version: "1.0"
- serviceName: project.siqagitandtpp.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAGitAndTPPProject
    version: "1.0"
configurationVariables:
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.user
  : sa
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.blockingTimeout
  : "5000"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.expireTimeout
  : "5000"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.keyStore
  : ""
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionEnabled
  : "false"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.maximumPoolSize
  : "20"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.trustStore
  : ""
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQAGitAndTPPProject.project.siqagitandtpp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabaseNewAccount.connectionManagerSettings.startupRetryCount
  : "0"
